#!/bin/sh
# Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#runs every crashreport AFL finds for a specified header.
#run with ./crash.sh <Device_Type>
DEVICE=$1

if [ $DEVICE = "help" ]
	then
		echo "To run this script:"
		echo "./crash.sh <Device_Type>"
		exit
	fi
if [ -z "$1" ]
	then
		echo "Please provide a device type and offset after \"./run.sh\""
		echo "ex. ./crash.sh ABC"
		exit
	fi
if [ ! -d ../include/$DEVICE ]
	then
		echo "There is no ../include/$DEVICE directory"
		exit
	fi
if [ ! -f ../include/$DEVICE/boot.img ]
	then
		echo "There is no boot.img in the ../include/$DEVICE directory"
		exit
	fi

if [ ! -d out/$DEVICE ]
	then
		mkdir -p out/$DEVICE
	fi
# Get the page size of the image
PAGE_SIZE=`od -j 36 -t x4 -N 4 -An ../include/$DEVICE/boot.img`
PAGE_SIZE=`echo "ibase=16; $PAGE_SIZE" | bc`

#find every offset that has at least one crash report
cd output/$DEVICE
grep -r "unique_crashes " | sed 's/[^0-9 || ^ ]*//g' > ../../out/$DEVICE/crashes.txt
sed -i '/ 0/d' ../../out/$DEVICE/crashes.txt
awk '{print $1}' ../../out/$DEVICE/crashes.txt | sort -n > ../../out/$DEVICE/crash_offsets.txt
cd ../..

#for every offset with at least one crash, run them all
while IFS=' ' read OFFSET
do
	#Every AFL crash report starts with an id
	cd output/$DEVICE/$OFFSET/crashes
	ls | grep "id" > ../../../../out/$DEVICE/files.txt
	cd ../../../..

	while IFS=' '  read -r crashreport
	do
	#Detect how big the header is
	if [ ! -f testcases/$DEVICE/$OFFSET/signature.bin ]
		then
			echo "This script uses the testcases generated by run.sh to calculate the correct header size."\
				"Please run that at least once to generate the proper testcases for this device"
			exit
		fi
	HEADER_SIZE=$(stat --printf="%s" testcases/$DEVICE/$OFFSET/signature.bin)
	if [ $HEADER_SIZE -gt 0 ]
		then
			echo
			echo
			echo "running offset: $OFFSET, with crash: $crashreport"
			echo
			out/signature_test_tool $OFFSET $HEADER_SIZE $PAGE_SIZE $DEVICE output/$DEVICE/$OFFSET/crashes/$crashreport
		fi
	done <"out/$DEVICE/files.txt"
done <"out/$DEVICE/crash_offsets.txt"
