#!/bin/sh
# Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.

#This script will generate boot.img files with inputs that caused crashes from AFL
#It will automatically create a boot image for each crash report in output/<device>/<offset>/crashes
#Run with ./synthesize.sh <Device_type> <offset>
DEVICE=$1
OFFSET=$2

if [ $1 = "help" ]
	then
		echo "To run this script:"
		echo "./run.sh <Device_Type> <offset>"
		echo
		echo "To get a valid boot.img:"
		echo "If the device type you want to test is not in the"
		echo "/include directory, download the latest userdebug build"
		echo "from KBITS, extract it, copy the 'boot.img' located in"
		echo "it, and make a new directory in"
		echo "signature_test_tools_libtomcrypt/include/<Device_type>"
		echo "named after the device and insert the boot.img"
		echo "file in to it."
		exit
	fi
if [ -z "$2" ]
	then
		echo "Please provide a device and offset after \"./run.sh\""
		echo "ex. ./run.sh ABC 0"
		exit
	fi
if [ ! -d ../include/$1 ]
	then
		echo "There is no ../include/$1 directory"
		exit
	fi
if [ ! -f ../include/$1/boot.img ]
	then
		echo "There is no boot.img in the ../include/$1 directory"
		exit
	fi

if [ ! -f testcases/$DEVICE/$OFFSET/signature.bin ]
	then
		echo "This script uses the testcases generated by run.sh to calculate the correct header size."\
			"Please run that at least once to generate the proper testcases for this device"
		exit
	fi

#Detect page size
PAGE_SIZE=`od -j 36 -t x4 -N 4 -An ../include/$DEVICE/boot.img`
PAGE_SIZE=`echo "ibase=16; $PAGE_SIZE" | bc`

#Detect size of boot.img
BOOT_IMAGE_SIZE=$(stat --printf "%s" ../include/$DEVICE/boot.img)
if [ ! -d out/$DEVICE ]
then
	mkdir -p out/$DEVICE
fi
if [ ! -d corrupted_images/$DEVICE/$OFFSET ]
then
	mkdir -p corrupted_images/$DEVICE/$OFFSET
fi

#Find all crashes. AFL formats crashes beginning with "id:"
ls output/$DEVICE/$OFFSET/crashes | grep "id:"> corrupted_images/$DEVICE/$OFFSET/crashes.txt

#If there are no crashes exit
if [ ! -s corrupted_images/$DEVICE/$OFFSET/crashes.txt ]
then
	echo "there are no crashes for this device and offset"
	exit
fi

#Trim boot.img up to the specified header offset
head  -c $(($BOOT_IMAGE_SIZE-$PAGE_SIZE+$OFFSET)) ../include/$DEVICE/boot.img > corrupted_images/$DEVICE/$OFFSET/boot.img

#Detect size of header at offset
OFFSET_SIZE=$(stat --printf "%s" testcases/$DEVICE/$OFFSET/signature.bin)

#Create image for each crash
while IFS=' '  read -r crashreport
do
	if [ ! -d  corrupted_images/$DEVICE/$OFFSET/$crashreport ]
		then
			mkdir corrupted_images/$DEVICE/$OFFSET/$crashreport
		fi
	cat corrupted_images/$DEVICE/$OFFSET/boot.img output/$DEVICE/$OFFSET/crashes/$crashreport > corrupted_images/$DEVICE/$OFFSET/$crashreport/boot.img
	tail -c $(($PAGE_SIZE-$OFFSET-$OFFSET_SIZE)) ../include/$DEVICE/boot.img >> corrupted_images/$DEVICE/$OFFSET/$crashreport/boot.img
done <"corrupted_images/$DEVICE/$OFFSET/crashes.txt"
rm -f corrupted_images/$DEVICE/$OFFSET/boot.img
