#
# Copyright 2019 Amazon.com, Inc. or its Affiliates. All rights reserved. 
#
LOCAL_PATH := $(GET_LOCAL_DIR)

INCLUDES += -I$(LOCAL_PATH) \
	-I$(LOCAL_PATH)/include \
	-I$(LOCAL_PATH)/include/openssl \
	-I$(LOCAL_PATH)/crypto \
	-I$(LOCAL_PATH)/crypto/bn \
	-I$(LOCAL_PATH)/crypto/asn1 \
	-I$(LOCAL_PATH)/crypto/bf \
	-I$(LOCAL_PATH)/crypto/conf \
	-I$(LOCAL_PATH)/crypto/evp \
	-I$(LOCAL_PATH)/crypto/modes \
	-I$(LOCAL_PATH)/crypto/objects \
	-I$(LOCAL_PATH)/crypto/ripemd \
	-I$(LOCAL_PATH)/crypto/rsa \
	-I$(LOCAL_PATH)/crypto/sha \
	-I$(LOCAL_PATH)/crypto/x509v3 \

# Default OpenSSL CFLAGS
CFLAGS += -DOPENSSL_BN_ASM_MONT \
		-DAES_ASM \
		-DSHA1_ASM \
		-DSHA256_ASM \
		-DSHA512_ASM \
		-DNO_WINDOWS_BRAINDEATH \
		-DOPENSSL_IMPLEMENTS_strncasecmp \
		-DGETPID_IS_MEANINGLESS \
		-DOPENSSL_THREADS \
		-D_REENTRANT \
		-DDSO_DLFCN \
		-DHAVE_DLFCN_H \
		-DZLIB \
		-DL_ENDIAN

# Disable un-necessary crypto algos
CFLAGS += -DOPENSSL_NO_CAMELLIA \
		-DOPENSSL_NO_CAPIENG \
		-DOPENSSL_NO_CAST \
		-DOPENSSL_NO_CMS \
		-DOPENSSL_NO_STDIO \
		-DOPENSSL_NO_GMP \
		-DOPENSSL_NO_IDEA \
		-DOPENSSL_NO_JPAKE \
		-DOPENSSL_NO_MD2 \
		-DOPENSSL_NO_MDC2 \
		-DOPENSSL_NO_RC2 \
		-DOPENSSL_NO_RC4 \
		-DOPENSSL_NO_RC5 \
		-DOPENSSL_NO_BF \
		-DOPENSSL_NO_SHA0 \
		-DOPENSSL_NO_RFC3779 \
		-DOPENSSL_NO_SEED \
		-DOPENSSL_NO_STORE \
		-DOPENSSL_NO_WHIRLPOOL \
		-DOPENSSL_NO_MD4 \
		-DOPENSSL_NO_MD5 \
		-DOPENSSL_NO_DES \
		-DOPENSSL_NO_OCSP \
		-DOPENSSL_NO_AES \
		-DOPENSSL_NO_DSA \
		-DOPENSSL_NO_DH \
		-DOPENSSL_NO_SHA512 \
		-DOPENSSL_NO_HW \
		-DOPENSSL_NO_ENGINE \
		-DOPENSSL_NO_EC2M \
		-DOPENSSL_NO_PKCS12 \
		-DOPENSSL_NO_EC \
		-DOPENSSL_NO_ECDSA

CFLAGS += -DOPENSSL_SYS_LK -DOPENSSL_NO_HMAC -DNO_STDERR -DNO_ABORT -DNO_TIME \
		-DNO_STRCASECMP -DOPENSSL_NO_FP_API -DOPENSSL_NO_SSCANF -DNO_SSLV23 \
		-DOPENSSL_NO_OBJECT

OBJS += \
	$(LOCAL_PATH)/qsort.o \
        $(LOCAL_PATH)/crypto/cryptlib.o \
        $(LOCAL_PATH)/crypto/mem.o \
        $(LOCAL_PATH)/crypto/mem_clr.o \
        $(LOCAL_PATH)/crypto/mem_dbg.o \
        $(LOCAL_PATH)/crypto/cversion.o \
        $(LOCAL_PATH)/crypto/ex_data.o \
        $(LOCAL_PATH)/crypto/cpt_err.o \
        $(LOCAL_PATH)/crypto/ebcdic.o \
        $(LOCAL_PATH)/crypto/o_str.o \
        $(LOCAL_PATH)/crypto/o_init.o \
	$(LOCAL_PATH)/crypto/asn1/a_bitstr.o \
        $(LOCAL_PATH)/crypto/asn1/a_bool.o \
        $(LOCAL_PATH)/crypto/asn1/a_bytes.o \
        $(LOCAL_PATH)/crypto/asn1/a_d2i_fp.o \
        $(LOCAL_PATH)/crypto/asn1/a_digest.o \
        $(LOCAL_PATH)/crypto/asn1/a_dup.o \
        $(LOCAL_PATH)/crypto/asn1/a_enum.o \
        $(LOCAL_PATH)/crypto/asn1/a_i2d_fp.o \
        $(LOCAL_PATH)/crypto/asn1/a_int.o \
        $(LOCAL_PATH)/crypto/asn1/a_mbstr.o \
        $(LOCAL_PATH)/crypto/asn1/a_object.o \
        $(LOCAL_PATH)/crypto/asn1/a_octet.o \
        $(LOCAL_PATH)/crypto/asn1/a_print.o \
        $(LOCAL_PATH)/crypto/asn1/a_sign.o \
        $(LOCAL_PATH)/crypto/asn1/a_strnid.o \
        $(LOCAL_PATH)/crypto/asn1/a_strex.o \
        $(LOCAL_PATH)/crypto/asn1/a_time.o \
        $(LOCAL_PATH)/crypto/asn1/a_type.o \
        $(LOCAL_PATH)/crypto/asn1/a_utctm.o \
        $(LOCAL_PATH)/crypto/asn1/a_utf8.o \
        $(LOCAL_PATH)/crypto/asn1/a_verify.o \
        $(LOCAL_PATH)/crypto/asn1/ameth_lib.o \
        $(LOCAL_PATH)/crypto/asn1/asn1_err.o \
        $(LOCAL_PATH)/crypto/asn1/asn1_lib.o \
        $(LOCAL_PATH)/crypto/asn1/asn1_par.o \
        $(LOCAL_PATH)/crypto/asn1/asn_mime.o \
        $(LOCAL_PATH)/crypto/asn1/asn_moid.o \
        $(LOCAL_PATH)/crypto/asn1/asn_pack.o \
	$(LOCAL_PATH)/crypto/asn1/bio_asn1.o \
        $(LOCAL_PATH)/crypto/asn1/d2i_pr.o \
        $(LOCAL_PATH)/crypto/asn1/d2i_pu.o \
        $(LOCAL_PATH)/crypto/asn1/evp_asn1.o \
        $(LOCAL_PATH)/crypto/asn1/f_enum.o \
        $(LOCAL_PATH)/crypto/asn1/f_int.o \
        $(LOCAL_PATH)/crypto/asn1/f_string.o \
        $(LOCAL_PATH)/crypto/asn1/i2d_pr.o \
        $(LOCAL_PATH)/crypto/asn1/i2d_pu.o \
        $(LOCAL_PATH)/crypto/asn1/n_pkey.o \
        $(LOCAL_PATH)/crypto/asn1/p5_pbe.o \
        $(LOCAL_PATH)/crypto/asn1/p8_pkey.o \
        $(LOCAL_PATH)/crypto/asn1/t_bitst.o \
        $(LOCAL_PATH)/crypto/asn1/t_crl.o \
        $(LOCAL_PATH)/crypto/asn1/t_req.o \
        $(LOCAL_PATH)/crypto/asn1/t_spki.o \
        $(LOCAL_PATH)/crypto/asn1/t_x509.o \
        $(LOCAL_PATH)/crypto/asn1/t_x509a.o \
        $(LOCAL_PATH)/crypto/asn1/tasn_enc.o \
        $(LOCAL_PATH)/crypto/asn1/tasn_dec.o \
        $(LOCAL_PATH)/crypto/asn1/tasn_fre.o \
        $(LOCAL_PATH)/crypto/asn1/tasn_new.o \
        $(LOCAL_PATH)/crypto/asn1/tasn_prn.o \
        $(LOCAL_PATH)/crypto/asn1/tasn_typ.o \
        $(LOCAL_PATH)/crypto/asn1/tasn_utl.o \
        $(LOCAL_PATH)/crypto/asn1/x_algor.o \
        $(LOCAL_PATH)/crypto/asn1/x_attrib.o \
        $(LOCAL_PATH)/crypto/asn1/x_bignum.o \
        $(LOCAL_PATH)/crypto/asn1/x_crl.o \
        $(LOCAL_PATH)/crypto/asn1/x_exten.o \
        $(LOCAL_PATH)/crypto/asn1/x_info.o \
        $(LOCAL_PATH)/crypto/asn1/x_long.o \
        $(LOCAL_PATH)/crypto/asn1/x_name.o \
        $(LOCAL_PATH)/crypto/asn1/x_nx509.o \
        $(LOCAL_PATH)/crypto/asn1/x_pkey.o \
        $(LOCAL_PATH)/crypto/asn1/x_pubkey.o \
        $(LOCAL_PATH)/crypto/asn1/x_req.o \
        $(LOCAL_PATH)/crypto/asn1/x_sig.o \
        $(LOCAL_PATH)/crypto/asn1/x_spki.o \
        $(LOCAL_PATH)/crypto/asn1/x_val.o \
        $(LOCAL_PATH)/crypto/asn1/x_x509.o \
        $(LOCAL_PATH)/crypto/asn1/x_x509a.o \
        $(LOCAL_PATH)/crypto/bio/bio_lib.o \
        $(LOCAL_PATH)/crypto/bio/b_print.o \
	$(LOCAL_PATH)/crypto/bn/asm/armv4-mont.o \
	$(LOCAL_PATH)/crypto/bn/bn_add.o \
	$(LOCAL_PATH)/crypto/bn/bn_asm.o \
	$(LOCAL_PATH)/crypto/bn/bn_blind.o \
	$(LOCAL_PATH)/crypto/bn/bn_ctx.o \
	$(LOCAL_PATH)/crypto/bn/bn_div.o \
	$(LOCAL_PATH)/crypto/bn/bn_err.o \
	$(LOCAL_PATH)/crypto/bn/bn_exp.o \
	$(LOCAL_PATH)/crypto/bn/bn_exp2.o \
	$(LOCAL_PATH)/crypto/bn/bn_gcd.o \
	$(LOCAL_PATH)/crypto/bn/bn_gf2m.o \
	$(LOCAL_PATH)/crypto/bn/bn_kron.o \
	$(LOCAL_PATH)/crypto/bn/bn_lib.o \
	$(LOCAL_PATH)/crypto/bn/bn_mod.o \
	$(LOCAL_PATH)/crypto/bn/bn_mont.o \
	$(LOCAL_PATH)/crypto/bn/bn_mpi.o \
	$(LOCAL_PATH)/crypto/bn/bn_mul.o \
	$(LOCAL_PATH)/crypto/bn/bn_nist.o \
	$(LOCAL_PATH)/crypto/bn/bn_prime.o \
	$(LOCAL_PATH)/crypto/bn/bn_print.o \
	$(LOCAL_PATH)/crypto/bn/bn_recp.o \
	$(LOCAL_PATH)/crypto/bn/bn_shift.o \
	$(LOCAL_PATH)/crypto/bn/bn_sqr.o \
	$(LOCAL_PATH)/crypto/bn/bn_sqrt.o \
	$(LOCAL_PATH)/crypto/bn/bn_word.o \
	$(LOCAL_PATH)/crypto/buffer/buf_err.o \
        $(LOCAL_PATH)/crypto/buffer/buf_str.o \
        $(LOCAL_PATH)/crypto/buffer/buffer.o \
        $(LOCAL_PATH)/crypto/conf/conf_api.o \
        $(LOCAL_PATH)/crypto/conf/conf_def.o \
        $(LOCAL_PATH)/crypto/conf/conf_err.o \
        $(LOCAL_PATH)/crypto/conf/conf_lib.o \
        $(LOCAL_PATH)/crypto/conf/conf_mall.o \
        $(LOCAL_PATH)/crypto/err/err.o \
        $(LOCAL_PATH)/crypto/err/err_all.o \
        $(LOCAL_PATH)/crypto/err/err_prn.o \
	$(LOCAL_PATH)/crypto/evp/c_all.o \
        $(LOCAL_PATH)/crypto/evp/c_allc.o \
        $(LOCAL_PATH)/crypto/evp/c_alld.o \
        $(LOCAL_PATH)/crypto/evp/digest.o \
        $(LOCAL_PATH)/crypto/evp/e_aes.o \
        $(LOCAL_PATH)/crypto/evp/e_bf.o \
        $(LOCAL_PATH)/crypto/evp/e_des.o \
        $(LOCAL_PATH)/crypto/evp/e_des3.o \
        $(LOCAL_PATH)/crypto/evp/e_null.o \
        $(LOCAL_PATH)/crypto/evp/e_old.o \
        $(LOCAL_PATH)/crypto/evp/e_rc2.o \
        $(LOCAL_PATH)/crypto/evp/e_rc4.o \
        $(LOCAL_PATH)/crypto/evp/e_rc5.o \
        $(LOCAL_PATH)/crypto/evp/e_xcbc_d.o \
        $(LOCAL_PATH)/crypto/evp/encode.o \
        $(LOCAL_PATH)/crypto/evp/evp_acnf.o \
        $(LOCAL_PATH)/crypto/evp/evp_enc.o \
        $(LOCAL_PATH)/crypto/evp/evp_err.o \
        $(LOCAL_PATH)/crypto/evp/evp_key.o \
        $(LOCAL_PATH)/crypto/evp/evp_lib.o \
        $(LOCAL_PATH)/crypto/evp/evp_pkey.o \
        $(LOCAL_PATH)/crypto/evp/m_dss.o \
        $(LOCAL_PATH)/crypto/evp/m_dss1.o \
        $(LOCAL_PATH)/crypto/evp/m_mdc2.o \
        $(LOCAL_PATH)/crypto/evp/m_null.o \
        $(LOCAL_PATH)/crypto/evp/m_ripemd.o \
        $(LOCAL_PATH)/crypto/evp/m_sha1.o \
        $(LOCAL_PATH)/crypto/evp/m_sigver.o \
        $(LOCAL_PATH)/crypto/evp/m_wp.o \
        $(LOCAL_PATH)/crypto/evp/names.o \
        $(LOCAL_PATH)/crypto/evp/p5_crpt.o \
        $(LOCAL_PATH)/crypto/evp/p5_crpt2.o \
        $(LOCAL_PATH)/crypto/evp/p_dec.o \
        $(LOCAL_PATH)/crypto/evp/p_enc.o \
        $(LOCAL_PATH)/crypto/evp/p_lib.o \
        $(LOCAL_PATH)/crypto/evp/p_open.o \
        $(LOCAL_PATH)/crypto/evp/p_seal.o \
        $(LOCAL_PATH)/crypto/evp/p_sign.o \
        $(LOCAL_PATH)/crypto/evp/p_verify.o \
        $(LOCAL_PATH)/crypto/evp/pmeth_fn.o \
        $(LOCAL_PATH)/crypto/evp/pmeth_gn.o \
        $(LOCAL_PATH)/crypto/evp/pmeth_lib.o \
        $(LOCAL_PATH)/crypto/lhash/lh_stats.o \
        $(LOCAL_PATH)/crypto/lhash/lhash.o \
        $(LOCAL_PATH)/crypto/modes/cbc128.o \
        $(LOCAL_PATH)/crypto/modes/cfb128.o \
        $(LOCAL_PATH)/crypto/modes/ofb128.o \
        $(LOCAL_PATH)/crypto/objects/obj_dat.o \
        $(LOCAL_PATH)/crypto/objects/obj_err.o \
        $(LOCAL_PATH)/crypto/objects/obj_lib.o \
        $(LOCAL_PATH)/crypto/objects/obj_xref.o \
        $(LOCAL_PATH)/crypto/objects/o_names.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_ameth.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_asn1.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_chk.o \
	$(LOCAL_PATH)/crypto/rsa/rsa_crpt.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_eay.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_err.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_gen.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_lib.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_none.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_null.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_oaep.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_pk1.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_pmeth.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_prn.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_pss.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_sign.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_saos.o \
        $(LOCAL_PATH)/crypto/rsa/rsa_x931.o \
        $(LOCAL_PATH)/crypto/sha/sha1_one.o \
        $(LOCAL_PATH)/crypto/sha/sha1dgst.o \
        $(LOCAL_PATH)/crypto/sha/sha256.o \
        $(LOCAL_PATH)/crypto/sha/sha512.o \
        $(LOCAL_PATH)/crypto/sha/sha_dgst.o \
	$(LOCAL_PATH)/crypto/sha/asm/sha1-armv4-large.o \
	$(LOCAL_PATH)/crypto/sha/asm/sha256-armv4.o \
        $(LOCAL_PATH)/crypto/stack/stack.o \
        $(LOCAL_PATH)/crypto/ts/ts_err.o \
        $(LOCAL_PATH)/crypto/txt_db/txt_db.o \
        $(LOCAL_PATH)/crypto/x509/x509_att.o \
        $(LOCAL_PATH)/crypto/x509/x509_cmp.o \
        $(LOCAL_PATH)/crypto/x509/x509_d2.o \
        $(LOCAL_PATH)/crypto/x509/x509_def.o \
        $(LOCAL_PATH)/crypto/x509/x509_err.o \
        $(LOCAL_PATH)/crypto/x509/x509_ext.o \
        $(LOCAL_PATH)/crypto/x509/x509_lu.o \
        $(LOCAL_PATH)/crypto/x509/x509_obj.o \
        $(LOCAL_PATH)/crypto/x509/x509_r2x.o \
        $(LOCAL_PATH)/crypto/x509/x509_req.o \
        $(LOCAL_PATH)/crypto/x509/x509_set.o \
        $(LOCAL_PATH)/crypto/x509/x509_trs.o \
        $(LOCAL_PATH)/crypto/x509/x509_txt.o \
        $(LOCAL_PATH)/crypto/x509/x509_v3.o \
        $(LOCAL_PATH)/crypto/x509/x509_vfy.o \
        $(LOCAL_PATH)/crypto/x509/x509_vpm.o \
        $(LOCAL_PATH)/crypto/x509/x509cset.o \
        $(LOCAL_PATH)/crypto/x509/x509name.o \
        $(LOCAL_PATH)/crypto/x509/x509rset.o \
        $(LOCAL_PATH)/crypto/x509/x509spki.o \
        $(LOCAL_PATH)/crypto/x509/x509type.o \
        $(LOCAL_PATH)/crypto/x509/x_all.o \
	$(LOCAL_PATH)/crypto/x509v3/pcy_cache.o \
        $(LOCAL_PATH)/crypto/x509v3/pcy_data.o \
        $(LOCAL_PATH)/crypto/x509v3/pcy_lib.o \
        $(LOCAL_PATH)/crypto/x509v3/pcy_map.o \
        $(LOCAL_PATH)/crypto/x509v3/pcy_node.o \
        $(LOCAL_PATH)/crypto/x509v3/pcy_tree.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_akey.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_akeya.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_alt.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_bcons.o \
	$(LOCAL_PATH)/crypto/x509v3/v3_bitst.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_conf.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_crld.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_enum.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_genn.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_int.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_lib.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_ncons.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_pcons.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_pku.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_pmaps.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_prn.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_purp.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_skey.o \
        $(LOCAL_PATH)/crypto/x509v3/v3err.o \
        $(LOCAL_PATH)/crypto/x509v3/v3_utl.o

FUTURE_OBJS += \
	$(LOCAL_PATH)/crypto/ec/ec_ameth.o \
	$(LOCAL_PATH)/crypto/ec/ec_pmeth.o \
	$(LOCAL_PATH)/crypto/ec/ec_key.o \
	$(LOCAL_PATH)/crypto/ec/ec_lib.o \
	$(LOCAL_PATH)/crypto/ec/ec_curve.o \
	$(LOCAL_PATH)/crypto/ec/ec_asn1.o \
	$(LOCAL_PATH)/crypto/ec/ec_oct.o \
	$(LOCAL_PATH)/crypto/ec/ecp_oct.o \
	$(LOCAL_PATH)/crypto/ec/ec2_oct.o \
	$(LOCAL_PATH)/crypto/ec/ec_cvt.o \
	$(LOCAL_PATH)/crypto/ec/ec2_smpl.o \
	$(LOCAL_PATH)/crypto/ec/ecp_smpl.o \
	$(LOCAL_PATH)/crypto/ec/ecp_mont.o \
	$(LOCAL_PATH)/crypto/ec/ec_mult.o \
	$(LOCAL_PATH)/crypto/ec/ec2_mult.o \
	$(LOCAL_PATH)/crypto/ecdsa/ecs_sign.o \
	$(LOCAL_PATH)/crypto/ecdsa/ecs_asn1.o \
	$(LOCAL_PATH)/crypto/ecdsa/ecs_ossl.o \
	$(LOCAL_PATH)/crypto/ecdsa/ecs_vrf.o \
	$(LOCAL_PATH)/crypto/ecdsa/ecs_lib.o
	#$(LOCAL_PATH)/crypto/pkcs12/p12_add.o \
        $(LOCAL_PATH)/crypto/pkcs12/p12_asn.o \
        $(LOCAL_PATH)/crypto/pkcs12/p12_attr.o \
        $(LOCAL_PATH)/crypto/pkcs12/p12_crpt.o \
        $(LOCAL_PATH)/crypto/pkcs12/p12_crt.o \
        $(LOCAL_PATH)/crypto/pkcs12/p12_decr.o \
        $(LOCAL_PATH)/crypto/pkcs12/p12_init.o \
        $(LOCAL_PATH)/crypto/pkcs12/p12_key.o \
        $(LOCAL_PATH)/crypto/pkcs12/p12_kiss.o \
        $(LOCAL_PATH)/crypto/pkcs12/p12_mutl.o \
        $(LOCAL_PATH)/crypto/pkcs12/p12_npas.o \
        $(LOCAL_PATH)/crypto/pkcs12/p12_p8d.o \
        $(LOCAL_PATH)/crypto/pkcs12/p12_p8e.o \
        $(LOCAL_PATH)/crypto/pkcs12/p12_utl.o \
        $(LOCAL_PATH)/crypto/pkcs12/pk12err.o \
        $(LOCAL_PATH)/crypto/pkcs7/pk7_asn1.o \
        $(LOCAL_PATH)/crypto/pkcs7/pk7_attr.o \
        $(LOCAL_PATH)/crypto/pkcs7/pk7_doit.o \
        $(LOCAL_PATH)/crypto/pkcs7/pk7_lib.o \
        $(LOCAL_PATH)/crypto/pkcs7/pk7_mime.o \
        $(LOCAL_PATH)/crypto/pkcs7/pk7_smime.o \
        $(LOCAL_PATH)/crypto/pkcs7/pkcs7err.o \
